source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Mattermost' do
 	pod 'Alamofire', '~> 4.0'
	pod 'SwiftyJSON', '3.1'
	pod 'Kingfisher', '~> 3.1'
	pod 'Locksmith'
	pod 'R.swift'
	pod 'Unbox'
	pod 'Typist'
end