source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Mattermost' do
	pod 'SwiftyJSON', '3.1'
	pod 'Kingfisher', '~> 3.1'
	pod 'Locksmith'
	pod 'R.swift'
	pod 'ObjectMapper'
	pod 'Typist'
	pod 'Moya', '8.0.0-beta.4'
	pod 'Unbox'
end
